# Generated by Django 5.1.2 on 2024-11-05 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rating_ratinguser_alter_rating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie.moviedetails'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'ratingUser')},
        ),
        migrations.CreateModel(
            name='ReportMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportReason', models.CharField(max_length=100)),
                ('movieName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviedetails')),
            ],
        ),
    ]
